name: Test and Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - '**/*'
              

jobs:
    test:
        runs-on: ubuntu-latest
        
        
        
        steps:
            # Setting up the environment
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.9

            - name: Docker Setup
              uses: docker/setup-buildx-action@v2

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install flake8
            
            # Test the Code
            - name: Run Linting Tests
              run: |
                flake8 --ignore=E501,F401 .

            - name: Docker Credentials  
              uses: docker/login-action@v2
              with:
               username: ${{ secrets.DOCKER_USERNAME }}
               password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker tag
              id: version
              run: |
                VERSION=v$(date +'%Y%m%d%H%M%S')
                echo "VERSION=$VERSION" >> $GITHUB_ENV 
           
            # Build the Docker Image
            - name: Build Docker Image
              run: |
                docker build . -t korlins/demo-app:${{ env.VERSION }}

            # Push the Docker Image
            - name: Push Docker Image
              run: |
                docker push korlins/demo-app:${{ env.VERSION }}
            
            # Update the k8s manifest file
            - name: Update k8s manifest file
              run: |
                cat deploy/deploy.yaml
                sed -i "s|image: korlins/demo-app:.*|image: korlins/demo-app:${{ env.VERSION }}|g" deploy/deploy.yaml
                cat deploy/deploy.yaml

            # Update Github
            - name: Commit the changes
              run: |
                git config --global user.email "<collenito@gmail.com>"
                git config --global user.name "github-actions[bot]"
                git add deploy/deploy.yaml
                git commit -m "Update k8s manifest with new image version - ${{ env.VERSION }}"
                git remote set-url origin https://github.actions:${{ secrets.GITHUB_TOKEN }}@github.com/korlins/
                Flask-App-Github-Actions-ArgoCD.git
                git push origin master
              
              
            